language: php
php:
  - '7.1'
  - nightly
install: travis_retry composer install --no-interaction --prefer-source
script: vendor/bin/phpunit --coverage-text --coverage-clover=coverage.xml --colors
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.xml