sudo: required
language: php
services:
  - docker
php:
  - '7.1'
  - nightly
before_install:
  - echo "extension=redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - cp ./app/config/parameters.yml.dist ./app/config/parameters.yml
  - cp ./app/config/parameters_permanent.yml.dist ./app/config/parameters_permanent.yml
  - cp ./docker-compose.yml.dist ./docker-compose.yml
  - docker-compose up -d
install:
  - travis_retry composer install --no-interaction --prefer-source
  - npm install
script: vendor/bin/phpunit --coverage-text --coverage-clover=coverage.xml --colors
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.xml