# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    # controllers are imported separately to make sure they're public
    # and have a tag that allows actions to type-hint services
    Wishlist\Http\Controller\:
        resource: '../../src/Http/Controller'
        public: true
        tags: ['controller.service_arguments']

    Wishlist\Domain\WishRepositoryInterface:
        class: Wishlist\Infrastructure\Persistence\Doctrine\WishRepository
        autowire: true

    Symfony\Component\Cache\Adapter\TagAwareAdapterInterface:
        class: Symfony\Component\Cache\Adapter\TagAwareAdapterInterface
        factory: [Wishlist\Infrastructure\Cache\TagAwareAdapterFactory, createAdapter]
        arguments:
            - '@cache.app'

    wishlist.wish.repository:
        class: Wishlist\Infrastructure\Persistence\Common\CachingWishRepository
        arguments:
            - '@Wishlist\Domain\WishRepositoryInterface'
            - '@Symfony\Component\Cache\Adapter\TagAwareAdapterInterface'

    wishlist.currency.factory:
        class: Wishlist\Infrastructure\Currency\DefaultCurrencyFactory
        public: true
        factory: [Wishlist\Infrastructure\Currency\DefaultCurrencyFactory, createCurrency]
        arguments:
            - '%default_currency_code%'

    Wishlist\Application\WishlistInterface:
        class: Wishlist\Application\Wishlist
        arguments:
            - '@wishlist.wish.repository'
            - "@=service('wishlist.currency.factory')"

    wishlist.event_listener.wish_not_found:
        class: Wishlist\Http\EventListener\WishNotFoundExceptionListener
        tags:
            - { name: kernel.event_listener, event: kernel.exception }
