Wishlist\Domain\Deposit:
    type: entity
    table: deposits
    id:
        id:
            type: deposit_id
            generator:
                strategy: none
    manyToOne:
        wish:
            targetEntity: Wishlist\Domain\Wish
            inversedBy: deposits
            joinColumn:
                name: wish_id
                referencedColumnName: id
                nullable: false
    embedded:
        amount:
            class: Money\Money
            columnPrefix: false
    fields:
        createdAt:
            type: datetime
            nullable: false
            column: created_at