Wishlist\Domain\Moneybox:
    type: embeddable
    oneToMany:
        deposits:
            targetEntity: Wishlist\Domain\Deposit
            mappedBy: wish
            orphanRemoval: true
            orderBy:
                createdAt: DESC
            cascade: [persist]